### ISSUE TITLE
HTTP 500 Error with Public Server

### ISSUE THREAD

**Issue by DefCon42** [vrtadmin/FIRST-plugin-ida#29]
The public FIRST server seems to be down; every request generates a 500 error as far as I can tell.

For reference: 
```
Server: first.talosintelligence.com
Port: 443
Protocol: HTTPS
Verify: No
Valid API key
```

I can't seem to find some other contact form on the website, so I'll just submit this here.

**Comment by xabiugarte** [comment]
Hi DefCon42,

I am wondering if this was a temporary error. I have just tested it, and it seems to work correctly. Also, please consider changing the "Verify" option to "Yes"; the server has a valid certificate.

I am assigning myself to follow this up. Please let me know if you are still having issues.

Thanks,

**Comment by DefCon42** [comment]
Hm, interesting. The plugin still seems to fail, and directly querying the browser with https://first.talosintelligence.com/api/test_connection/(api_key) seems to break as well.

**Comment by xabiugarte** [comment]
![image](https://user-images.githubusercontent.com/5371486/69940057-50768b80-14af-11ea-8680-c1078ac18cfe.png)

Are you by any chance behind a proxy?

**Comment by DefCon42** [comment]
No, but I can try connecting through a VPN and see if anything changes.

**Comment by DefCon42** [comment]
![image](https://user-images.githubusercontent.com/5364774/69940403-35f0e200-14b0-11ea-9227-cb57f0873db6.png)

Seems to be the only response I get.

**Comment by DefCon42** [comment]
![image](https://user-images.githubusercontent.com/5364774/69940444-5751ce00-14b0-11ea-9605-76ac3bda51b9.png)
Seems to be the only response I get.

**Comment by xabiugarte** [comment]
Can you try with an intentionally wrong API key to see if you get an "unauthorized" response?

**Comment by DefCon42** [comment]
An invalid API key also returns a 500 error.

![image](https://user-images.githubusercontent.com/5364774/69964973-5b4a1400-14e1-11ea-90ed-590f260983fc.png)

**Comment by xabiugarte** [comment]
Hi DefCon42,

Sorry for the delay. Was the API key you used a lower case uuid? If so, could you try to send the same request with an uppercase API key against first.talosintelligence.com? Please let us know if that solves the issue.
We have corrected an incorrect URL handling bug, that was refusing to accept lower_case API keys. The FIRST-sever repository has been updated (https://github.com/vrtadmin/FIRST-server/commit/bc114d44725436fe2ea569bf01a3891812baf32d) and the changes will be pushed to production shortly.

Sorry for the inconveniences, and thanks again for reporting the error! I will keep this issue open until we update the production server.

**Comment by DefCon42** [comment]
Yep, that seems to have fixed it. Interesting because copy-pasting the API key from the website profile page shows uppercase letters but copies lowercase ones.

**Comment by taodaqiao** [comment]
![image](https://user-images.githubusercontent.com/33372680/72600625-fa6e8200-394e-11ea-8497-a54899bc1943.png)

HTTP 500 Error with Public Server

**Comment by jimmy-sonny** [comment]
Production server has been updated. Closing the issue.
