### ISSUE TITLE
Bug: Block IDA if upload error

### ISSUE THREAD

**Issue by grimaz** [vrtadmin/FIRST-plugin-ida#3]
If uploading error occurs pop-up 'Please wait..' window can not be cancelled and block IDA Pro.
Log contains last strings
first.py, line 3116, in __data
msg = '[1st] Error: {}'.format(result['msg'])
NameError: global name 'result' is not defined

**Comment by demonduck** [comment]
fix for this issue is now in master branch. Thanks for creating the issue.
