### ISSUE TITLE
Can't establish connection with server

### ISSUE THREAD

**Issue by qfrtt** [vrtadmin/FIRST-plugin-ida#31]
Hi, 
I can't seem to configure properly the plugin

![image](https://user-images.githubusercontent.com/9437677/78100998-1dd49500-73b4-11ea-82eb-8fe9f734749f.png)

**Comment by xabiugarte** [comment]
Hi, there have been some issues with python requests and Cloudfare in the past. Please, make sure that you are using the latest version of the plugin from the master branch.

Also, please try to run the following python script so that we can get a more informative error of what is going on:

`import requests
import sys

g_network_headers = {}

VERSION = 'BETA'
DATE = 'May 2018'

g_network_headers['User-Agent'] = "FIRST {} {} Cython {}({}.{}.{}) {}".format(
    VERSION,
    DATE,
    sys.api_version,
    sys.version_info.major,
    sys.version_info.minor,
    sys.version_info.releaselevel,
    sys.platform
    )

print("WITHOUT HEADERS")
print("===============")
r = requests.get("https://first.talosintelligence.com/api/test_connection/YOUR_API_KEY")
print(r.status_code)
print(r.text)

print("WITH HEADERS")
print("============")
r = requests.get("https://first.talosintelligence.com/api/test_connection/YOUR_API_KEY", headers=g_network_headers)
print(r.status_code)
print(r.text)
import requests
import sys

g_network_headers = {}

VERSION = 'BETA'
DATE = 'May 2018'

g_network_headers['User-Agent'] = "FIRST {} {} Cython {}({}.{}.{}) {}".format(
    VERSION,
    DATE,
    sys.api_version,
    sys.version_info.major,
    sys.version_info.minor,
    sys.version_info.releaselevel,
    sys.platform
    )

print("WITHOUT HEADERS")
print("===============")
r = requests.get("https://first.talosintelligence.com/api/test_connection/YOUR_API_KEY")
print(r.status_code)
print(r.text)

print("WITH HEADERS")
print("============")
r = requests.get("https://first.talosintelligence.com/api/test_connection/YOUR_API_KEY", headers=g_network_headers)
print(r.status_code)
print(r.text)
`

**Comment by qfrtt** [comment]
Hi,

Here's the output

`WITHOUT HEADERS
===============
403
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | first.talosintelligence.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 57eeaa9c6ad1f981 &bull; 2020-04-04 23:04:05 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>

          </div>



        </div>
      </div>

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>57eeaa9c6ad1f981</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 67.216.57.56</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>

WITH HEADERS
============
200
{"status" : "connected"}
WITHOUT HEADERS
===============
403
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | first.talosintelligence.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 57eeaa9e881ff981 &bull; 2020-04-04 23:04:06 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>

          </div>



        </div>
      </div>

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>57eeaa9e881ff981</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 67.216.57.56</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>

WITH HEADERS
============
200
{"status" : "connected"}`

**Comment by xabiugarte** [comment]
Can you make sure that you are using the latest version of the plugin from the master branch?

It seems that everything is working on your end when the proper headers are used in the request. 

This fix was merged into master some time ago.

**Comment by qfrtt** [comment]
Yep fixed it thx
