### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by BigJim** [vrtadmin/FIRST-plugin-ida#32]
What does this plugin actually do, what is it good for?  
I'm asking and it's what others will ask because it the description is just:
> Function Identification and Recovery Signature Tool  

And the documentation link leads to what looks generic on first look:
https://first-plugin-ida.readthedocs.io/en/latest/

No intro, etc. No offense, and thanks for releasing your tools (I think), but it helps to sell people on what something is to see if we want to use it first.

**Comment by xabiugarte** [comment]
Hello,

You can read a description of the project in the [official website](https://first.talosintelligence.com/) . If you need more information, there are links to the whitepaper and presentation in the [Talos Intelligence website for the project](https://talosintelligence.com/first).

Thanks

**Comment by BigJim** [comment]
Thanks much. Looks useful. Sort of like IDA's Lumina feature right?
Suggestion, maybe put this link at the top of your README.rst files.
