### ISSUE TITLE
Add more API mappings

### ISSUE THREAD

**Issue by Grazfather** [vrtadmin/FIRST-plugin-ida#33]
I am working on a simple IDA plugin and found your IDAW wrapper (See https://github.com/hugsy/gef/pull/510)

There are a bunch of mappings that could be added to get it to work better. See https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

A tiny subset, that works for my plugin, at least:

```
        'GetBptEA' : 'get_bpt_ea',
        'GetBptQty' : 'get_bpt_qty',
        'GetColor' : 'get_color',
        'Jump' : 'jumpto',
        'MakeComm' : 'set_cmt',
        'MakeName' : 'set_name',
        'SetColor' : 'set_color',
```

**Comment by Grazfather** [comment]
Look at hugsy/gef#553. The above doesn't work perfectly because some commands take extra args. My linked PR fixes this, and I think does the safe_generator thing better, feel free to pilfer.

**Comment by jimmy-sonny** [comment]
Thanks @Grazfather for the advices. We will address the problem with a new plugin version compatible with IDA 7.3+. The issue is related to https://github.com/vrtadmin/FIRST-plugin-ida/issues/30.
